### ISSUE TITLE
[FEATURE REQUEST] Add special <title> tag to http website

### ISSUE THREAD

**Issue by twofaktor** [Yonle/bostr#13]
When you access the [webpage](https://github.com/Yonle/bostr/blob/master/http.js) version, the title of the tab shows the domain/subdomain related to the bouncer like this:

![imagen](https://github.com/Yonle/bostr/assets/89636253/bd3efa11-3e0f-42d0-877c-265d4e0547cd)

To better identify on bookmarks or when you have the webpage opened, my suggestion is to add a concrete title instead of the domain/subdomain related to connect with the bouncer, like **"Bostr; The nostr relay bouncer"** + the domain/subdomain related or only **"Bostr; The nostr relay bouncer"** or some name related to the project

**Comment by Yonle** [comment]
We are serving plain text, not an HTML.

And we do not need to do that except doing it with reverse proxy.
