### ISSUE TITLE
Feature Idea: Blacklist

### ISSUE THREAD

**Issue by mroxso** [Yonle/bostr#15]
I was wondering if a Blacklist implementation would be possible?

Like known scamming and spamming npubs could be blocked to write to this relay.

But more important:
It would be great if no event of a blacklisted npub would come through the relay.

What you are thinking about this?

**Comment by Yonle** [comment]
Similiar feature is already available.

There are whitelist already.
Check `approved_publishers` in `config.js.example`

> It would be great if no event of a blacklisted npub would come through the relay.

Useless. The suspect will be able to create another pubkey to bypass it so there's almost no use for implementing blacklist for nostr.
