### ISSUE TITLE
Oversubscribing

### ISSUE THREAD

**Issue by v0l** [Yonle/bostr#17]
Hello,

Please respect concurrent request limits as defined in the relay document, i noticed a lot of logs for Bostr relays sending too many concurrent requests.

stryfry:
`sending error to [15356]: too many concurrent REQs`

**Comment by Yonle** [comment]
Currently bostr did not check for relay's NIP-11. I have no plan to do it as the main goal of the project itself is mostly for personal use.

Normally you could actually ignore this warning (as it does not really seems impacting the upstream relay performance). But as it could be annoying for admins that monitors their relay activity, then i may going to implement NIP-11 checking.

**Comment by Yonle** [comment]
Checking via NIP-11 is still not considered reliable as far as i could tell. Sometime even without the `limitation` field, the relay is still limiting.

You may make strfry code to not need to log this kind of error as it does not really seems impacting on performance that much. The exceeding subscription limit could be completely ignored in relay side.

But feel free to tell me what do you think.
