### ISSUE TITLE
[Suggestion] Replace relays info for load balancer info on http.js when not relays are set

### ISSUE THREAD

**Issue by twofaktor** [Yonle/bostr#19]
Hello, using this feature:

![Captura de pantalla 2024-05-12 232416](https://github.com/Yonle/bostr/assets/89636253/1205ee8b-c28a-4aeb-80b7-c16797f6f8f2)

Due to this, relays connected info appears empty and I think relays info should be replaced with load balancer info on `http.js` when no relays are set so users know which relays they are connecting to under the hood

![Captura de pantalla 2024-05-12 232350](https://github.com/Yonle/bostr/assets/89636253/00618f5c-da77-49d3-8fcf-43abe61f19ec)

**Comment by Yonle** [comment]
```
// NOTE: You will need to make sure that these bouncers has the same relays list as the other bouncers did,
//       Otherwise the listing page of this http server will be inaccurate.
//
// ATTENTION: This load balancer is ONLY designed for bouncers in mimd.
//            If you REALLY want to use it with your relays, Ensure that
//            Every single relays that you provide below is using the same database as the others did.
```

Just added this into master. Can you test it? If you are using source code then just `git pull` and restart. Or if you are using npm installation, Then `npm i -g https://github.com/Yonle/bostr.git`

**Comment by twofaktor** [comment]
![imagen](https://github.com/Yonle/bostr/assets/89636253/3d124b6f-8dc4-458f-8af8-53c6e42049b6)

Some unknown error

**Comment by Yonle** [comment]
Forgot to mention that you need to install new pkg for it. Run `npm i` and try again

**Comment by twofaktor** [comment]
> Forgot to mention that you need to install new pkg for it. Run `npm i` and try again

It didn't solve anything

**Comment by Yonle** [comment]
> > Forgot to mention that you need to install new pkg for it. Run `npm i` and try again
> 
> It didn't solve anything

Paste the error please.

**Comment by Yonle** [comment]
Just saw the error. Fixed. Try `git pull` or `npm i -g` (look at prev. command that i sent) again.

**Comment by twofaktor** [comment]
```
May 13 00:05:09 minibolt2fa systemd[1]: Started Nostr relay bouncer (Bostr).
May 13 00:05:10 minibolt2fa node[869577]: Primary 869577 is running. Will fork 1 clusters.
May 13 00:05:10 minibolt2fa node[869584]: node:internal/modules/cjs/loader:1148
May 13 00:05:10 minibolt2fa node[869584]:   throw err;
May 13 00:05:10 minibolt2fa node[869584]:   ^
May 13 00:05:10 minibolt2fa node[869584]: Error: Cannot find module 'undici'
May 13 00:05:10 minibolt2fa node[869584]: Require stack:
May 13 00:05:10 minibolt2fa node[869584]: - /home/nostr/bostr/http.js
May 13 00:05:10 minibolt2fa node[869584]: - /home/nostr/bostr/index.js
May 13 00:05:10 minibolt2fa node[869584]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
May 13 00:05:10 minibolt2fa node[869584]:     at Module._load (node:internal/modules/cjs/loader:986:27)
May 13 00:05:10 minibolt2fa node[869584]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
May 13 00:05:10 minibolt2fa node[869584]:     at require (node:internal/modules/helpers:179:18)
May 13 00:05:10 minibolt2fa node[869584]:     at Object.<anonymous> (/home/nostr/bostr/http.js:11:16)
May 13 00:05:10 minibolt2fa node[869584]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 13 00:05:10 minibolt2fa node[869584]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 13 00:05:10 minibolt2fa node[869584]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
May 13 00:05:10 minibolt2fa node[869584]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
May 13 00:05:10 minibolt2fa node[869584]:     at Module.require (node:internal/modules/cjs/loader:1233:19) {
May 13 00:05:10 minibolt2fa node[869584]:   code: 'MODULE_NOT_FOUND',
May 13 00:05:10 minibolt2fa node[869584]:   requireStack: [ '/home/nostr/bostr/http.js', '/home/nostr/bostr/index.js' ]
May 13 00:05:10 minibolt2fa node[869584]: }
May 13 00:05:10 minibolt2fa node[869584]: Node.js v20.13.1
May 13 00:05:10 minibolt2fa node[869577]: Worker 869584 died. Forking another one....
May 13 00:05:10 minibolt2fa node[869596]: node:internal/modules/cjs/loader:1148
May 13 00:05:10 minibolt2fa node[869596]:   throw err;
May 13 00:05:10 minibolt2fa node[869596]:   ^
May 13 00:05:10 minibolt2fa node[869596]: Error: Cannot find module 'undici'
May 13 00:05:10 minibolt2fa node[869596]: Require stack:
May 13 00:05:10 minibolt2fa node[869596]: - /home/nostr/bostr/http.js
May 13 00:05:10 minibolt2fa node[869596]: - /home/nostr/bostr/index.js
May 13 00:05:10 minibolt2fa node[869596]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
May 13 00:05:10 minibolt2fa node[869596]:     at Module._load (node:internal/modules/cjs/loader:986:27)
May 13 00:05:10 minibolt2fa node[869596]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
May 13 00:05:10 minibolt2fa node[869596]:     at require (node:internal/modules/helpers:179:18)
May 13 00:05:10 minibolt2fa node[869596]:     at Object.<anonymous> (/home/nostr/bostr/http.js:11:16)
May 13 00:05:10 minibolt2fa node[869596]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 13 00:05:10 minibolt2fa node[869596]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 13 00:05:10 minibolt2fa node[869596]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
May 13 00:05:10 minibolt2fa node[869596]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
May 13 00:05:10 minibolt2fa node[869596]:     at Module.require (node:internal/modules/cjs/loader:1233:19) {
May 13 00:05:10 minibolt2fa node[869596]:   code: 'MODULE_NOT_FOUND',
May 13 00:05:10 minibolt2fa node[869596]:   requireStack: [ '/home/nostr/bostr/http.js', '/home/nostr/bostr/index.js' ]
May 13 00:05:10 minibolt2fa node[869596]: }
May 13 00:05:10 minibolt2fa node[869596]: Node.js v20.13.1
May 13 00:05:10 minibolt2fa node[869577]: Worker 869596 died. Forking another one....
May 13 00:05:10 minibolt2fa node[869604]: node:internal/modules/cjs/loader:1148
May 13 00:05:10 minibolt2fa node[869604]:   throw err;
May 13 00:05:10 minibolt2fa node[869604]:   ^
May 13 00:05:10 minibolt2fa node[869604]: Error: Cannot find module 'undici'
May 13 00:05:10 minibolt2fa node[869604]: Require stack:
May 13 00:05:10 minibolt2fa node[869604]: - /home/nostr/bostr/http.js
May 13 00:05:10 minibolt2fa node[869604]: - /home/nostr/bostr/index.js
May 13 00:05:10 minibolt2fa node[869604]:     at Module._resolveFilename (node:internal/modules/cjs/loader:1145:15)
May 13 00:05:10 minibolt2fa node[869604]:     at Module._load (node:internal/modules/cjs/loader:986:27)
May 13 00:05:10 minibolt2fa node[869604]:     at Module.require (node:internal/modules/cjs/loader:1233:19)
May 13 00:05:10 minibolt2fa node[869604]:     at require (node:internal/modules/helpers:179:18)
May 13 00:05:10 minibolt2fa node[869604]:     at Object.<anonymous> (/home/nostr/bostr/http.js:11:16)
May 13 00:05:10 minibolt2fa node[869604]:     at Module._compile (node:internal/modules/cjs/loader:1358:14)
May 13 00:05:10 minibolt2fa node[869604]:     at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
May 13 00:05:10 minibolt2fa node[869604]:     at Module.load (node:internal/modules/cjs/loader:1208:32)
May 13 00:05:10 minibolt2fa node[869604]:     at Module._load (node:internal/modules/cjs/loader:1024:12)
May 13 00:05:10 minibolt2fa node[869604]:     at Module.require (node:internal/modules/cjs/loader:1233:19) {
May 13 00:05:10 minibolt2fa node[869604]:   code: 'MODULE_NOT_FOUND',
May 13 00:05:10 minibolt2fa node[869604]:   requireStack: [ '/home/nostr/bostr/http.js', '/home/nostr/bostr/index.js' ]
May 13 00:05:10 minibolt2fa node[869604]: }
May 13 00:05:10 minibolt2fa node[869604]: Node.js v20.13.1
May 13 00:05:10 minibolt2fa node[869577]: Worker 869604 died. Forking another one....
May 13 00:05:10 minibolt2fa node[869612]: node:internal/modules/cjs/loader:1148
May 13 00:05:10 minibolt2fa node[869612]:   throw err;
May 13 00:05:10 minibolt2fa node[869612]:   ^
```

This looped after trying to start again.

**Comment by twofaktor** [comment]
> Just saw the error. Fixed. Try `git pull` or `npm i -g` (look at prev. command that i sent) again.

Ok, it was solved. I tested the last changes that you made, and I think it should be polished

It obtains and shows the next section of options, check it out yourself:
![imagen](https://github.com/Yonle/bostr/assets/89636253/78144e03-a1d0-4fe8-a07a-e9f5492be456)

https://bouncer.minibolt.info/ <-- "slave" bouncer
https://bouncer.nostree.me/ <-- "master" bouncer

**Comment by twofaktor** [comment]
Does it make sense if I connect to relay/s and load balancer/s simultaneously?

Anyway: If I do that, it doesn't show on http.js the load balancer/s that I have connected and the relays connected to him, only the relay/s that I have connected, does that make sense?

**Comment by Yonle** [comment]
> Does it make sense if I connect to relay/s and load balancer/s simultaneously?

The load balancer does not connect to these bouncers simultaneously.

> Anyway: If I do that, it doesn't show on http.js the load balancer/s that I have connected and the relays connected to him, only the relay/s that I have connected, does that make sense?

It won't make sense. That just makes me reimplementing another bouncer code which is practically useless.

**Comment by twofaktor** [comment]
> > Just saw the error. Fixed. Try `git pull` or `npm i -g` (look at prev. command that i sent) again.
> 
> Ok, it was solved. I tested the last changes that you made, and I think it should be polished
> 
> It obtains and shows the next section of options of the "master" bouncer too, check it out yourself:
> 
> ![imagen](https://private-user-images.githubusercontent.com/89636253/329889975-78144e03-a1d0-4fe8-a07a-e9f5492be456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODg4ODksIm5iZiI6MTcxNTU4ODU4OSwicGF0aCI6Ii84OTYzNjI1My8zMjk4ODk5NzUtNzgxNDRlMDMtYTFkMC00ZmU4LWEwN2EtZTlmNTQ5MmJlNDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTM5ZmMwYmUxMGZiODQ0Yzc4ZGZhMGFkMDA3MGQ4NzZkMzNkYzk2NDkwOGYxYzY1NTY3ZTg3MDBkZGI4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVPKledyTobB9peS2F5iMww7i_iJKmvBDzFTgp79kXE) "slave" bouncer -------------------------------------------------------------------------------- "master" bouncer

What do you think about this? Is it correct?

**Comment by Yonle** [comment]
> > > Just saw the error. Fixed. Try `git pull` or `npm i -g` (look at prev. command that i sent) again.
> > 
> > Ok, it was solved. I tested the last changes that you made, and I think it should be polished
> > 
> > It obtains and shows the next section of options of the "master" bouncer too, check it out yourself:
> > 
> > ![imagen](https://private-user-images.githubusercontent.com/89636253/329889975-78144e03-a1d0-4fe8-a07a-e9f5492be456.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU1ODg4ODksIm5iZiI6MTcxNTU4ODU4OSwicGF0aCI6Ii84OTYzNjI1My8zMjk4ODk5NzUtNzgxNDRlMDMtYTFkMC00ZmU4LWEwN2EtZTlmNTQ5MmJlNDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTEzVDA4MjMwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQzOTM5ZmMwYmUxMGZiODQ0Yzc4ZGZhMGFkMDA3MGQ4NzZkMzNkYzk2NDkwOGYxYzY1NTY3ZTg3MDBkZGI4ZGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVPKledyTobB9peS2F5iMww7i_iJKmvBDzFTgp79kXE) "slave" bouncer -------------------------------------------------------------------------------- "master" bouncer
> 
> What do you think about this? Is it correct? Does it need a fix?

There are something to do with the regex. I will think of fixing it

**Comment by Yonle** [comment]
Just pushed a change to upstream to improve the listing. Let me know if things going well.

**Comment by Yonle** [comment]
Got network problem when pushing. The new commit should be here now.

**Comment by twofaktor** [comment]
> Got network problem when pushing. The new commit should be here now.

Nice, now it makes more sense, BTW a good new feature is the load balancer, thanks!

![imagen](https://github.com/Yonle/bostr/assets/89636253/336984cc-26c1-4309-b7bd-ecc30b95e61c)
