### ISSUE TITLE
Public bouncer causing relays to be overloaded

### ISSUE THREAD

**Issue by Darecjo** [Yonle/bostr#3]
IS Bostr connected to several relays at once ? Because it is causing relays to shut off very rapidly and it is not practical. Can someone clear the way Bostr works ?

**Comment by alexgleason** [comment]
Unfortunately relays limit the number of subscriptions per IP to a really low number (as low as 10 for some software). I've built a similar piece of software as this one, and I'm facing problems. The only way around it is by using firehose filters (`{ limit: 0 }`) and caching _everything_. I see no other way when you're serving multiple users. This only works if there's 1 user for the entire server.

**Comment by Darecjo** [comment]
I'm rebooting the relays daily because of the overload tons of connection workers are coming out from bostr. Consuming subscriptions per clients  should me optimized or we all gonna need heavy specs for it which is costy. as @alexgleason said the best way is to cache and serve same way primal.net is doing with their cache server.

**Comment by Yonle** [comment]
bostr was actually never supposed to run in a public space, and i was expecting this results in return by relays operator already even as an public bostr operator.

**Comment by Yonle** [comment]
> as @alexgleason said the best way is to cache and serve same way primal.net is doing with their cache server.

I am not here for the caching, and therefore making it remains inaccurate. It's simply making it to become another nostr relay software before i even implemented caching.

But let's see, I think i could do caching relay+bostr approach.

**Comment by Darecjo** [comment]
I'm here to inform you of what i experienced and maybe other relays operators are experiencing if they are not well aware of this its gonna cost them. the nginx `access.log` was at its max with connection coming from bostr. Hope things get optimized, because the idea behind it seems great.

**Comment by Yonle** [comment]
> the nginx access.log was at its max with connection coming from bostr. 

I could not avoid this in public bouncer.
Now send me your relay address so i remove it on the relay list.

**Comment by Darecjo** [comment]
nah its all good i increased the `worker_connections` within the `nginx.conf` and everything seems okay. If I faced other issues I will let you know for sure. Keep it up!

**Comment by Yonle** [comment]
Implemented caching and this should improve stuffs at relay owner's side.

**Comment by Darecjo** [comment]
Awsome!! Lets see how things go

**Comment by Yonle** [comment]
Not really reliable i would say.

**Comment by Darecjo** [comment]
at least it lowers the case

**Comment by Yonle** [comment]
kek

**Comment by Yonle** [comment]
Will keep it open as of now.

**Comment by Darecjo** [comment]
Hey there, the problem is still existed. Could you please remove `wss://nostr-01.yakihonne.com` and `wss://nostr-02.yakihonne.com` from the bostr ? We are receiving several complaint about the relay sorry :/

**Comment by Yonle** [comment]
> Hey there, the problem is still existed. Could you please remove `wss://nostr-01.yakihonne.com` and `wss://nostr-02.yakihonne.com` from the bostr ? We are receiving several complaint about the relay sorry :/

I never added your relay into my bouncer. Check https://bostr.yonle.lecturify.net

If you are still unsure, Kindly emailing me the log of the IP address so i could do further check at yonle@lecturify.net

**Comment by Darecjo** [comment]
Someone else is forking the bouncer then later on i will check the ip address and let u know thanks

**Comment by Yonle** [comment]
Also ensure that the IP has been checked with rDNS. My server IP has it is rDNS pointing to my hostname, and my hostname IP addresses matches to the IP addresses.

![Screenshot_20231224-213745.png](https://github.com/Yonle/bostr/assets/63401712/42a9b6c1-cfda-4c56-a8cd-f1199d07d90d)

**Comment by Darecjo** [comment]
I will check and let you know thanks !

**Comment by Yonle** [comment]
> Someone else is forking the bouncer then later on i will check the ip address and let u know thanks 

They host.
Not fork.

**Comment by Darecjo** [comment]
That's what I mean yeah, if it's not forked it's not gonna be hosted XD

**Comment by Yonle** [comment]
Now this is none of my business. You will need to resolve it by yourself.

**Comment by Darecjo** [comment]
yeah for sure 👌

**Comment by mikedilger** [comment]
I've had to IP block some Bostr things because my tiny VPS can't handle the load and my other websites were breaking with spurious SSL connection errors (the connection dropped midway due to maximum connections I think).

Thank you for specifying the user agent. That allowed me to find this repo and add to this issue.

Blocked IP addresses: 3.112.93.248, 18.179.22.121, 35.78.122.7, and 54.150.146.254

**Comment by Yonle** [comment]
> I've had to IP block some Bostr things because my tiny VPS can't handle the load and my other websites were breaking with spurious SSL connection errors (the connection dropped midway due to maximum connections I think).
> 
> Thank you for specifying the user agent. That allowed me to find this repo and add to this issue.
> 
> Blocked IP addresses: 3.112.93.248, 18.179.22.121, 35.78.122.7, and 54.150.146.254
> 
> my relay: nostr.mikedilger.com

None of these were my VPS IP addresses anymore.

**Comment by Yonle** [comment]
**Any report on bostr abusing your nostr relay WILL NOT BE ACCEPTED IN THIS ISSUE**

Neither the IP addresses that you've provided were actually mine. It could be run by other persons other than me. I only have 2 running bostr instance and none of these bouncers has configured to connect to your relays. Please check the bostr website and see whenever your relay was actually configured here.

**Comment by Yonle** [comment]
For more further questions, Check this [nostr note](nostr:nostr:nevent1qqsylplhjgmnfzenp09wetd3jqa044zgy0g776de7mer9zhlxexfd4szyq685gmsjqx3nd8yw43zzk2w30d8q6h9c7zauz09nerqt7g6q06fcqcyqqqqqqgf9fw8f)

**Comment by Yonle** [comment]
Bostr version 2.0.2 has been released which should solve this issue.

**Comment by Darecjo** [comment]
I blocked the IP addresses and I think they initiate new instances or change the IP not sure. I just had to block a new set of IPs. @mikedilger here you go if you want to block them directly: 
```
35.77.222.166
43.207.216.182
54.150.146.254
35.74.22.255
157.90.99.13
43.206.138.102
```

**Comment by Yonle** [comment]
[it's best to not publish IP addresses, even for blocking purpose here]
