### ISSUE TITLE
[FEATURE REQUEST] Add favicon option

### ISSUE THREAD

**Issue by twofaktor** [Yonle/bostr#9]
Same as some relay implementations allow, I suggest adding an option to store and select a favicon on config and offer this to the clients that request it

Example:
https://github.com/scsibug/nostr-rs-relay/blob/master/config.toml#L19-L21

Example of a favicon.ico hosted on a relay:
https://relay.minibolt.info/favicon.ico

Result on clients, for example, Amethyst:

![Screenshot_20240108_190433_com vitorpamplona amethyst_edit_9782812779756](https://github.com/Yonle/bostr/assets/89636253/9e9b8c5a-487d-48e8-bf3f-bc0b456c306f)
![Screenshot_20240108_190634](https://github.com/Yonle/bostr/assets/89636253/23014633-57eb-4bae-9565-bdb32f9074cd)

**Comment by Yonle** [comment]
Done.
```
{
  favicon: "path/to/favicon.ico"
  ...
}
```
In `config.js`
